version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
