service: rest-api-sls-dynamodb

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev

resources:
  Resources:
    dynamodb: ${file(./resources/dynamodb.yml)}

functions:
  hello: ${file(./functions/hello.yml)}
